// Plain-language glossary for people who are new to the data (organizer FAQ, Part 2: "a new engineer, who may not
// be familiar with the data parameters and train behaviour"). Definitions are short; the Learn page has the longer story.
// Keys are matched case-insensitively as whole phrases inside machine-generated text (see components/Glossed.tsx).

export type Term = { term: string; short: string; why?: string; subsystem?: "door" | "acv" | "rail" | "shm" | "all" };

export const GLOSSARY: Term[] = [
  // Door
  { term: "motor-current integral", subsystem: "door", short: "Motor current added up over the whole movement (milliamp-seconds, mA·s). Roughly the electrical effort the door motor spent to open or close.",
    why: "When something resists the door — grit in the rail, a rubbing seal, a bent leaf — the motor works harder for longer, so this total rises." },
  { term: "current integral", subsystem: "door", short: "Same as the motor-current integral: motor current summed over the movement, in mA·s." },
  { term: "mA·s", subsystem: "door", short: "Milliamp-seconds: current (mA) multiplied by time (s). 2000 mA·s is e.g. 500 mA for 4 s." },
  { term: "cutoff", subsystem: "all", short: "The frozen decision line. Above it the cycle is called Abnormal resistance, at or below it Normal. It was fixed during training and is never moved by an upload." },
  { term: "baseline", subsystem: "door", short: "This recording's own typical Normal level for one direction — the 25th percentile of its cycles' current integrals. Used so a door that naturally draws a bit more current is not misjudged." },
  { term: "back electromotive force", subsystem: "door", short: "The voltage a spinning motor generates by itself (back-EMF). It rises with motor speed, so it tells you how fast the door was moving without a speed sensor." },
  { term: "back-EMF", subsystem: "door", short: "Back electromotive force: voltage generated by the motor's own rotation, proportional to speed." },
  { term: "Motor electrodynamic force", subsystem: "door", short: "The dataset's name for back-EMF: the voltage the motor generates by turning; higher when the door moves faster." },
  { term: "DCSR", subsystem: "door", short: "Door Close Switch, Right. A limit switch that is actuated when the right side of the door reaches the closed position; released while the door is open." },
  { term: "DCSL", subsystem: "door", short: "Door Close Switch, Left. Actuated when the left side reaches the closed position." },
  { term: "DLSR", subsystem: "door", short: "Door Locked Switch, Right. Actuated when the right lock engages after closing." },
  { term: "DLSL", subsystem: "door", short: "Door Locked Switch, Left. Actuated when the left lock engages." },
  { term: "door leaf position", subsystem: "door", short: "Where the door panel is along its travel (about 700 = closed, 0 = fully open in this data; the unit is not documented)." },
  { term: "cycle", subsystem: "door", short: "One complete opening or one complete closing movement, found in the continuous recording wherever the rows pause for more than a second." },
  { term: "abnormal resistance", subsystem: "door", short: "The door met more resistance than a healthy door does — a foreign object in the rail, a jamming rubber strip or a deformed leaf are typical causes. The recording shows the effect, not the cause." },
  // ACV
  { term: "refrigerant leak", subsystem: "acv", short: "Loss of the working fluid of the air-conditioning circuit. With less refrigerant the unit cannot move as much heat, so the cabin stays warmer than it should under load." },
  { term: "cooling target", subsystem: "acv", short: "The temperature the car's air-conditioning controller is trying to reach while cooling (the control temperature for cooling)." },
  { term: "peer residual", subsystem: "acv", short: "How much warmer (+) or cooler (−) a car's cabin is than the median of the other cars at the same moment, in kelvin. Comparing cars on the same train at the same time cancels the weather." },
  { term: "settled cooling", subsystem: "acv", short: "Cooling samples taken at least 10 minutes after the unit switched into a cooling mode, so the cabin has had time to respond." },
  { term: "active cooling", subsystem: "acv", short: "Running mode is Automatic, Full or Half Cooling — the unit is actually trying to cool. Stop, Ventilation and Emergency Ventilation are not cooling." },
  { term: "running mode", subsystem: "acv", short: "What the ACV unit is doing right now: Automatic Cooling, Full Cooling, Half Cooling, Ventilation, Emergency Ventilation, Stop, or Invalid (no valid reading)." },
  { term: "K", subsystem: "acv", short: "Kelvin, used here for temperature differences: +0.5 K means half a degree warmer. The sensors report in 0.5 K steps, so differences smaller than 0.5 K are within one sensor step." },
  { term: "rank-decay", subsystem: "acv", short: "The official ACV score: the true faulty car ranked 1st scores 1.0, 2nd 0.875, 3rd 0.75 … 8th 0.125 for an 8-car file." },
  // Rail
  { term: "rail corrugation", subsystem: "rail", short: "A periodic wavy wear pattern on the rail running surface (wavelength centimetres to tens of centimetres). Wheels running over it shake the axle boxes and make a roaring or squealing noise." },
  { term: "corrugation", subsystem: "rail", short: "Periodic wavy wear on the rail surface; it shakes the axle boxes as wheels run over it." },
  { term: "axle box", subsystem: "rail", short: "The bearing housing at each end of a wheel axle. An accelerometer bolted to it feels what the wheel feels from the rail." },
  { term: "axle-box", subsystem: "rail", short: "Relating to the axle box: the bearing housing at each wheel end that carries the vibration sensor." },
  { term: "Side I", subsystem: "rail", short: "One of the two rails. The axle boxes at positions 1, 3, 5 and 7 of every car run on it." },
  { term: "Side II", subsystem: "rail", short: "The other rail. The axle boxes at positions 2, 4, 6 and 8 of every car run on it." },
  { term: "RMS", subsystem: "all", short: "Root mean square — the typical magnitude of a vibrating signal (the size of the shaking, ignoring its sign). Units here are m/s²." },
  { term: "m/s²", subsystem: "rail", short: "Metres per second squared, the unit of acceleration. 9.8 m/s² is the acceleration of gravity." },
  { term: "fault-detection score", subsystem: "rail", short: "The model's vote (0 to 1) that a corrugation signature is present. 0.5 is the decision line. It is not a probability — it has not been calibrated against outcomes." },
  { term: "kurtosis", subsystem: "rail", short: "How 'spiky' a signal is compared with steady shaking. Sharp impacts raise it." },
  { term: "crest factor", subsystem: "rail", short: "Peak divided by RMS — another spikiness measure: a few big hits on a quiet background give a high crest factor." },
  { term: "Welch PSD", subsystem: "rail", short: "Power spectral density: how much vibration energy sits at each frequency, estimated with Welch's averaging method. Corrugation shows up as energy concentrated in a band." },
  { term: "speed pulse", subsystem: "rail", short: "The toothed-wheel sensor's 0/1 signal (90 teeth per wheel turn). Counting its transitions gives the speed, but the conversion to km/h is unverified so it is not shown; the model does not use speed." },
  { term: "shock", subsystem: "rail", short: "The second channel per axle box, recording sharp impacts alongside the vibration channel." },
  // SHM
  { term: "cumulative fatigue damage", subsystem: "shm", short: "How much of a structure's fatigue life a stretch of loading has used up, on a scale where 1.0 means the design criterion for failure is reached. 0.05 means 5 % of that criterion in this segment." },
  { term: "Miner's rule", subsystem: "shm", short: "Fatigue damage adds up: each stress cycle uses a fraction 1/N of the life, where N is how many such cycles the material could take. Sum the fractions over all cycles." },
  { term: "Miner-type damage", subsystem: "shm", short: "A damage value computed by summing each counted stress cycle's share of fatigue life (Miner's rule)." },
  { term: "rainflow", subsystem: "shm", short: "The standard way to cut a wiggly stress history into individual load cycles (like counting rain running down a pagoda roof). Each cycle has a range (peak-to-valley) and a mean." },
  { term: "stress cycle", subsystem: "shm", short: "One load-and-unload swing in the stress signal, with a range (how big the swing was)." },
  { term: "cycle range", subsystem: "shm", short: "Peak-to-valley size of one counted stress cycle. Damage grows very steeply with range (here as range to the power 5), so the few largest cycles matter most." },
  { term: "gate", subsystem: "shm", short: "Tiny wiggles smaller than the gate (5 stress units) are ignored before counting cycles; they carry almost no damage and would only add noise." },
  { term: "S–N curve", subsystem: "shm", short: "Stress–life curve: how many cycles (N) a material survives at each stress amplitude (S). Steeper stress → far fewer cycles." },
  { term: "peak-to-peak", subsystem: "shm", short: "The difference between the highest and lowest value of the signal." },
  { term: "MAPE", subsystem: "shm", short: "Mean absolute percentage error — how far off the estimates are, relative to the true value, averaged over files. The official SHM score is 1 − MAPE." },
  // Shared
  { term: "review suggested", subsystem: "all", short: "The prediction stands, but something about the evidence is unusual (near a decision line, outside the training range, a data problem). A person should look before acting on it alone." },
  { term: "training range", subsystem: "all", short: "The span of values seen in the labelled training data. Outside it, the model is extrapolating and its numbers are less trustworthy." },
  { term: "macro F1", subsystem: "rail", short: "The official Rail score: F1 for each of the three classes, averaged equally, so rare Side I / Side II cases count as much as Normal." },
  { term: "IoU", subsystem: "door", short: "Intersection over union of two time ranges — 1.0 when the predicted cycle's start and end match the true ones exactly." },
];

export function findTerm(text: string): Term | undefined {
  const t = text.toLowerCase();
  return GLOSSARY.find((g) => g.term.toLowerCase() === t);
}
